# Generated by Django 5.2.8 on 2025-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
